source/main/urls.py
from django.urls import path
from .views import *

app_name = "app"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("post", PostCreateView.as_view(), name="post_create"),
    path("post/<str:post_id>", PostView.as_view(), name="post_view"),
    path("post/<str:post_id>/edit", PostEditView.as_view(), name="post_edit"),
    path("post/<str:post_id>/delete", PostDelete.as_view(), name="post_delete"),
]

source/memories/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("", include("social_django.urls", namespace="social")),
]

source/main/models.py
import traceback
import facebook
import logging
import io
import urllib.request as request
from django.db import models
from django.core.files.base import File
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from social_django.models import UserSocialAuth
from location_field.models.plain import PlainLocationField


logger = logging.getLogger(__name__)


class Profile(models.Model):
    """
    Extends user model with additional information
    """

    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    avatar_img = models.ImageField(upload_to="user_avatar", null=True, blank=True)

    @property
    def avatar_url(self):
        if self.avatar_img:
            return self.avatar_img.url
        else:
            # Facebook's "default" avatar link
            return "http://graph.facebook.com/111/picture?type=small"

    def update_avatar_url(self):
        """
        Method handling updating this profile's avatar picture
        """
        try:
            # Get user access token from server database
            auth = UserSocialAuth.objects.get(user_id=self.user.id)
            auth_extra_data = auth.extra_data
            access_token = auth_extra_data["access_token"]
            fb_user_id = auth_extra_data["id"]
            logger.info("Facebook user ID acquired")

            # Intialize facebook graph API
            graph = facebook.GraphAPI(access_token=access_token)
            # Get avatar information
            avatar_data = graph.get_object(id=fb_user_id, fields="picture")
            avatar_link = avatar_data["picture"]["data"]["url"]

            # Read avatar to server's RAM
            img_response = request.urlretrieve(avatar_link)
            img_filename = img_response[0]

            # Save to blob storage
            with open(img_filename, "rb") as f:
                self.avatar_img.save(str(fb_user_id), File(f))

        except Exception as e:
            logger.error("Cannot fetch profile picture link for user: %d", self.user.id)
            logger.error(traceback.format_exc())


# Database trigger when a new user is created
@receiver(post_save, sender=User)
def create_profile_signal(sender, instance, created, **kwargs):
    # If a new user is created: create a new profile for it
    if created:
        Profile.objects.create(user=instance)

    if hasattr(instance, "profile"):
        instance.profile.save()


class Post(models.Model):
    """
    A post that can be uploaded by the user
    """

    user = models.ForeignKey(verbose_name="Username", to=User, on_delete=models.CASCADE)
    title = models.CharField(verbose_name="Post title", max_length=100)
    content = models.TextField(verbose_name="Post content")
    image = models.ImageField(
        verbose_name="Image",
        upload_to="post_images",
        null=True,
        blank=True,
        help_text="If you do not provide an image, a random image will be shown when displaying this post.",
    )
    place_name = models.CharField(
        verbose_name="Place name",
        max_length=255,
        default="",
        help_text="Enter some text here, and the map below will change",
    )
    location = PlainLocationField(
        based_fields=["place_name"],
        default="10.762622,106.660172",
        help_text="You can zoom, click on the map to  select a location",
    )
    date_created = models.DateTimeField(verbose_name="Date created", auto_now_add=True)

    @property
    def img_url(self):
        # Returns random image if this post is not attached with any
        if self.image:
            return self.image.url
        return "https://picsum.photos/1000/500"


# Updates the user profile picture after user authentication
def profile_picture_update_handler(
    strategy, user, response, details, is_new=False, *args, **kwargs
):
    logger.info("End of authentication process")
    logger.info(f"User id: {user}")

    profile = Profile.objects.get(user=user)
    profile.update_avatar_url()

source/main/forms.py
from django import forms
from django.forms import widgets
from .models import *


class PostForm(forms.ModelForm):
    """
    Form for creating and editing a post
    """

    class Meta:
        model = Post
        exclude = ["user", "date_created"]

source/main/views.py
import django.contrib.messages as messages
from django.conf import settings
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin as DefaultLoginRequiredMixin
from django.core.exceptions import *
from django.db import transaction
from django.http import Http404, HttpRequest, HttpResponseServerError
from django.shortcuts import redirect, render
from django.views.generic import View, ListView
from django.core.paginator import Paginator


from .forms import *


class LoginRequiredMixin(DefaultLoginRequiredMixin):
    raise_exception = True
    permission_denied_message = (
        "You do not have access to this content because you are not logged in"
        "\r\nPlease go back to our homepage."
    )


class HomeView(View):
    """
    View representing the home page
    """

    template_name = "home/home.html"
    MAX_POSTS = 9

    def get(self, request: HttpRequest):
        try:
            # If user not signed in, redirect to login page
            current_user = request.user
            if not current_user.is_authenticated:
                return redirect("app:login")

            # Get all posts for this user
            posts = Post.objects.filter(user=current_user).order_by("-date_created")
            paginator = Paginator(posts, self.MAX_POSTS)

            # Filter by page
            page_number = request.GET.get("page")
            print(page_number)
            if not page_number:
                page_number = 1
            page_obj = paginator.get_page(page_number)

            return render(
                request,
                self.template_name,
                {"page_obj": page_obj, "title": "Home", "current_user": current_user},
            )
        except Exception as e:
            if settings.DEBUG:
                raise e
            return HttpResponseServerError()


class LoginView(View):
    """
    View presenting the login page
    """

    template_name = "home/login.html"

    def get(self, request: HttpRequest):
        try:
            current_user = request.user

            # Don't let the user access the login page if they have logged in
            if current_user.is_authenticated:
                return redirect("app:home")

            return render(
                request,
                self.template_name,
                {"title": "Login", "current_user": current_user},
            )
        except Exception as e:
            if settings.DEBUG:
                raise e
            return HttpResponseServerError()


class LogoutView(LoginRequiredMixin, View):
    """
    View handling logout request
    """

    def get(self, request):
        try:
            auth_logout(request)
            return redirect("app:login")
        except Exception as e:
            if settings.DEBUG:
                raise e
            return HttpResponseServerError()


class BasePostCreateEditView(LoginRequiredMixin, View):
    """
    Base method for creating and editing a post
    """

    template_name = "post/post_create_edit.html"

    def _process_validation_err(self, request, form):
        # Get all errors from form
        form_errors = form.errors.get_json_data()
        # Send error messages to client
        for field in form_errors:
            msgs = form_errors[field]
            for msg in msgs:
                render_msg = msg["message"]
                messages.error(request, f"Error in field {field}: {render_msg}")
        # Redirect to same page
        return redirect("app:post_create")


class PostCreateView(BasePostCreateEditView):
    """
    Handle post creation page
    """

    def get(self, request: HttpRequest):
        try:
            current_user = request.user
            # Create new post for current user
            form = PostForm()
            return render(
                request,
                self.template_name,
                {
                    "action": "Create new",
                    "form": form,
                    "title": "New post",
                    "current_user": current_user,
                },
            )
        except Exception as e:
            if settings.DEBUG:
                raise e
            return HttpResponseServerError()

    def post(self, request: HttpRequest):
        try:
            # Create new form
            form = PostForm(request.POST, request.FILES)

            # Validate and append to DB
            if form.is_valid():
                with transaction.atomic():
                    post_obj = form.save(commit=False)
                    post_obj.user = request.user
                    post_obj.save()
                messages.success(request, "Successfully added a new post")
                return redirect("app:home")
            else:
                raise ValidationError(
                    "The data you have submitted is invalid. Please try again."
                )
        except ValidationError:
            return self._process_validation_err(request, form)
        except Exception as e:
            if settings.DEBUG:
                raise e
            return HttpResponseServerError()


class PostEditView(BasePostCreateEditView):
    """
    Handle post edit page
    """

    def get(self, request: HttpRequest, post_id):
        try:
            # Get requested post
            current_user = request.user
            post = Post.objects.get(id=post_id, user__username=current_user.username)

            # Populate form with item and send to client
            form = PostForm(instance=post)
            return render(
                request,
                self.template_name,
                {
                    "action": "Edit ",
                    "form": form,
                    "title": "Edit post",
                    "current_user": current_user,
                },
            )
        except Exception as e:
            if settings.DEBUG:
                raise e
            return HttpResponseServerError()

    def post(self, request: HttpRequest, post_id):
        try:
            # Get current user
            current_user = request.user

            # Get corresponding post
            post = Post.objects.get(id=post_id, user__username=current_user.username)

            # Populate form with edited data from client
            form = PostForm(request.POST, request.FILES, instance=post)

            # Validate and append to DB
            if form.is_valid():
                print(request.FILES)
                with transaction.atomic():
                    post_obj = form.save(commit=False)
                    post_obj.user = request.user
                    post_obj.save()
                messages.success(request, "Successfully edit the new post")
                return redirect("app:post_view", post_id)
            else:
                raise ValidationError(
                    "The data you have submitted is invalid. Please try again."
                )
        except ObjectDoesNotExist:
            raise Http404()
        except ValidationError:
            return self._process_validation_err(request, form)
        except Exception as e:
            if settings.DEBUG:
                raise e
            return HttpResponseServerError()


class PostView(LoginRequiredMixin, View):
    """
    View presenting content of a post
    """

    template_name = "post/view_post.html"

    def get(self, request: HttpRequest, post_id):
        try:
            # Get requested post
            current_user = request.user
            post = Post.objects.get(id=post_id, user__username=current_user.username)

            # Render to client
            return render(
                request,
                self.template_name,
                {"title": post.title, "current_user": current_user, "post": post},
            )
        except ObjectDoesNotExist:
            raise Http404()
        except Exception as e:
            raise e


class PostDelete(LoginRequiredMixin, View):
    """
    View handling post deletion
    """

    def get(self, request: HttpRequest, post_id):
        try:
            # Get requested post
            current_user = request.user
            post = Post.objects.get(id=post_id, user__username=current_user.username)

            # Delete it
            post.delete()

            messages.success(request, "The post has been deleted successfully")
            return redirect("app:home")

        except ObjectDoesNotExist:
            raise Http404()
        except Exception as e:
            if settings.DEBUG:
                raise e
            return HttpResponseServerError()

source/main/templates/post/post_create_edit.html
{% extends 'base/base.html' %}
{% load django_bootstrap5 %}

{% block header %}
    <div class="container-fluid bg-primary">
        <div class="container py-5 text-light">
            <h3>{{ action }} post</h3>
        </div>
    </div>
{% endblock header %}

{% block content %}
    <div class="container pt-3">
        <div class="py-4">
            <form action="" method="post" enctype="multipart/form-data" id="post-form">
                <div>
                </div>
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="OK" %}
                <div class="spinner-border d-none" id="form-spinner" role="status">
                    <span class="sr-only"></span>
                </div>
            </form>
        </div>
    </div>

    <script>
        // Hides the text box of the "location" (map) field
        // For aesthetic purposes, no sensitive data here
        $("document").ready(function() {
            $("#id_location").hide();
        });

        // After user clicks "OK", hide the button and replace with loading icon
        // If user clicks twice, 2 requests will be sent to the server
        // This is a temporary solution
        $("#post-form").on("submit", function() {
            $("#post-form > button[type=submit]").hide();
            $("#form-spinner").removeClass("d-none");
        });
    </script>
{% endblock content %}

source/main/templates/post/view_post.html
{% extends 'base/base.html' %}
{% load static %}

{% block header %}
    <link rel = "stylesheet" href = "http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
    <div class="container-fluid">
        <a href="{{ post.img_url }}">
            <div class="hero">
                <img src="{{ post.img_url }}" class="flex-1 hero-img"/>
                <div class="hero-text">
                    <h2>{{ post.title }}</h2>
    
                    <h4>{{ post.place_name }}</h4>
    
                    <div>{{ post.date_created }}</div>
    
                    <span class="d-none" id="post-location">{{ post.location }}</span>
                </div>
            </div>
        </a>
    </div>
{% endblock header %}

{% block content %}
    <!--POST OPTIONS-->
    <div class="container pt-4">
        <div class="pb-3">
            <div class="dropdown">
                <a class="text-decoration-none dropdown-toggle" role="button" data-bs-toggle="dropdown">
                  Post options
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li><a class="dropdown-item" href="{{ post.img_url }}">View full-size image</a></li>
                  <li><a class="dropdown-item" href="{% url 'app:post_edit' post.id %}">Edit</a></li>
                  <li>
                    <a role="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#postDeleteModal">
                        Delete
                    </a>
                  </li>
                </ul>
              </div>
        </div>
        
        <!--POST CONTENT-->
        <div class="row">
            <!--POST MAIN CONTENT-->
            <div class="col-md-8">
                <p class="text-justify">{{ post.content }}</p>
            </div>

            <!--POST MAP-->
            <div class="col-md-4">
                <div>
                    <div id="leaflet-container"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- MODAL FOR CONFIRM DELETE -->
    <div class="modal fade" id="postDeleteModal" tabindex="-1" aria-labelledby="postDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="postDeleteModalLabel">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Do you want to delete this post? This action cannot be undone.
            </div>
            <div class="modal-footer">
              <div class="modal-footer-control">
                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Cancel</button>
                <a class="btn btn-danger" id="btn-delete" href="{% url 'app:post_delete' post.id %}" role="button" class="btn btn-danger">Delete this post</a>
              </div>

              <div class="spinner-border d-none" id="delete-spinner" role="status">
                <span class="sr-only"></span>
              </div>
            </div>
          </div>
        </div>
      </div>

    <script src = "http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

    <script>
        // Get location data from form
        let locationStr = $('#post-location').text();
        let [lat, lon] = locationStr.split(',');
        
        let mapOptions = {
            center: [lat, lon],
            zoom: 15,
        }

        // Create new map and add marker
        let map = new L.map('leaflet-container', mapOptions);
        let layer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');
        
        map.addLayer(layer);
        let marker = L.marker([lat, lon]).addTo(map);

        
        // Hides the delete button after user clicks delete
        // If user clicks twice, 2 requests will be sent to the server
        // Causes no damage, but client will show error 404 (because the post was deleted before)
        // This is a temporary solution
        $("#btn-delete").on("click", function() {
          $(".modal-footer-control").hide();
          $("#delete-spinner").removeClass("d-none");
        });
    </script>
{% endblock content %}